test:
  DATABASE_URL: "postgres://postgres:@localhost:5432/onpoint_test"
  DATABASE_POOL: "5"
  REDISCLOUD_URL: "redis://localhost:9736/"
  REDIS_URL: "redis://localhost:9736/1"
  JWT_SECRET: jwt-secret-test-key
  JWT_ISSUER: localhost:5000

development:
  DATABASE_URL: "postgres://postgres:@localhost:5432/onpoint_development"
  DATABASE_POOL: "5"
  REDISCLOUD_URL: "redis://localhost:6379/"
  REDIS_URL: "redis://localhost:6379/1"
  JWT_SECRET: jwt-secret-development-key
  JWT_ISSUER: localhost:5000
